### ISSUE TITLE
CSS reset

### ISSUE THREAD

**Issue by BradleyHsu** [Hack-WashU/website#14]
Need to stick a css reset in the page so we get a consistent look over every web browser.

**Comment by jackheuberger** [comment]
From what I found online, Eric Meyer's [CSS Reset ](https://meyerweb.com/eric/tools/css/reset/) is the defacto standard.

**Comment by jackheuberger** [comment]
I think I did it correctly? I just took his and added an import in App.vue before importing the global style. Creating PR
